
CREATE TABLE user(
idUsuario VARCHAR(255) PRIMARY KEY NOT NULL,
username VARCHAR(255) NOT NULL,
email VARCHAR(200) NOT NULL,
password VARCHAR(200) NOT NULL,
password_hash VARCHAR(255) NOT NULL,
created_at DATE,
profile_url VARCHAR(255) NULL);

CREATE TABLE images(
idImage VARCHAR(255) PRIMARY KEY NOT NULL,
title VARCHAR(200) NOT NULL,
description VARCHAR(240) NULL,
url_img VARCHAR(255) NOT NULL,
extension VARCHAR(10) NOT NULL,
created_at DATE,
idUser VARCHAR(255) NOT NULL);

CREATE TABLE category(
idCategory INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nameCategory VARCHAR(100) NOT NULL);

CREATE TABLE cat_user(
idCatUser INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
idUser VARCHAR(255) NOT NULL,
idCategory INT NOT NULL);